version: "3"
service: 
  api:
    build: .
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    en_file:
      - ./.env
    
  posgres:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
  volumes:
   posgres-db: